Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = 2048
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.define "discovery" do |dis|
      dis.vm.hostname = "discovery.lab.com"
      dis.vm.network "private_network", ip: "192.168.33.30"
    end

    config.vm.define "coordinator" do |coordinator|
      coordinator.vm.hostname = "coordinator.lab.com"
      coordinator.vm.network "private_network", ip: "192.168.33.31"
    end

(2..3).each do |i|
    config.vm.define "worker0#{i}" do |worker|
        worker.vm.hostname = "worker0#{i}.lab.com"
        worker.vm.network "private_network", ip: "192.168.33.3#{i}"
    end
end

end